import { Link } from 'react-router-dom';

const dummyNotes = [
  {
    heading: "Introduction to Trading",
    text: `Trading is the act of buying and selling financial instruments with the aim of making a profit. It can be done in various markets such as stocks, forex, commodities, and cryptocurrencies. Successful trading requires a blend of technical analysis, risk management, and psychological discipline.`
  },
  {
    heading: "Understanding Buy/Sell Signals",
    text: `Buy and sell signals are indicators or triggers that suggest when to enter or exit a trade. These signals can be generated by technical indicators, price action, or algorithmic bots. It's important to validate signals with additional analysis before acting on them.`
  },
  {
    heading: "Risk Management",
    text: `Risk management is crucial in trading. Always use stop-loss orders, diversify your portfolio, and never risk more than a small percentage of your capital on a single trade. Consistent risk management helps protect your account from large losses.`
  },
  {
    heading: "Trading Psychology",
    text: `Emotions can greatly impact trading decisions. Maintaining discipline, sticking to your strategy, and avoiding impulsive trades are key to long-term success. Keep a trading journal to track your decisions and learn from your experiences.`
  },
  {
    heading: "Continuous Learning",
    text: `The financial markets are constantly evolving. Stay updated with the latest news, strategies, and technologies. Participate in trading communities, attend webinars, and never stop learning.`
  }
];

export default function SmartMoneyConcept() {
  return (
    <main
      className="course-detail-page"
      style={{
        padding: '2.5rem 0',
        width: '100%',
        margin: 0,
        background: 'linear-gradient(135deg, var(--bg-primary) 0%, var(--bg-secondary) 100%)',
        minHeight: '100vh',
        color: 'var(--text-primary)',
      }}
    >
      <Link
        to="/learning"
        style={{
          display: 'flex',
          alignItems: 'center',
          color: 'var(--text-secondary)',
          textDecoration: 'none',
          fontSize: '1rem',
          fontWeight: 500,
          marginBottom: 10,
          background: 'var(--card-bg)',
          border: '1.5px solid var(--border-color)',
          borderRadius: 8,
          padding: '0.5rem 1.1rem',
          boxShadow: '0 2px 8px rgba(0,0,0,0.07)',
          transition: 'background 0.2s, color 0.2s',
        }}
        onMouseOver={e => e.currentTarget.style.background = 'var(--hover-bg)'}
        onMouseOut={e => e.currentTarget.style.background = 'var(--card-bg)'}
      >
        <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg" style={{ marginRight: 6 }}>
          <path d="M13 16L7 10L13 4" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round"/>
        </svg>
        Back to Learning
      </Link>
      <h1 style={{
        color: 'var(--accent-color)',
        marginBottom: 28,
        fontSize: '2rem',
        fontWeight: 700,
        textAlign: 'center'
      }}>
        Smart Money Concept - Introduction Video
      </h1>
      <div
        style={{
          width: '100%',
          maxWidth: 600,
          margin: '0 auto 2.5rem auto',
          borderRadius: 16,
          overflow: 'hidden',
          background: 'var(--card-bg)',
          border: '1.5px solid var(--border-color)',
          boxShadow: '0 6px 32px 0 rgba(0,0,0,0.10)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          transition: 'box-shadow 0.2s',
        }}
      >
        <div style={{ position: 'relative', paddingBottom: '56.25%', height: 0, width: '100%' }}>
          <video
            src="https://www.w3schools.com/html/mov_bbb.mp4"
            controls
            style={{ position: 'absolute', top: 0, left: 0, width: '100%', height: '100%', background: '#000', borderRadius: 0 }}
          />
        </div>
      </div>
      {/* Notes below video */}
      <section
        style={{
          margin: 0,
          background: 'var(--card-bg)',
          borderRadius: 0,
          padding: '2.7rem 2vw',
          boxShadow: '0 4px 24px rgba(0,0,0,0.13)',
          width: '100%',
          color: 'var(--text-primary)',
        }}
      >
        <h2 style={{
          color: 'var(--accent-color)',
          marginBottom: 32,
          fontSize: '1.55rem',
          fontWeight: 700,
          textAlign: 'center'
        }}>
          Trading Notes & Educational Content
        </h2>
        {dummyNotes.map((note, idx) => (
          <div key={idx} style={{ marginBottom: 36 }}>
            <h3 style={{
              color: 'var(--accent-light)',
              marginBottom: 12,
              fontSize: '1.18rem',
              fontWeight: 600
            }}>{note.heading}</h3>
            <p style={{
              color: 'var(--text-secondary)',
              fontSize: '1.13rem',
              lineHeight: 1.8
            }}>{note.text}</p>
          </div>
        ))}
      </section>
      {/* Responsive adjustments */}
      <style>{`
        @media (max-width: 900px) {
          .course-detail-page {
            padding: 0.5rem 0 !important;
          }
          .course-detail-page section {
            padding: 1.2rem 0.5rem !important;
          }
        }
      `}</style>
    </main>
  );
} 